### ISSUE TITLE
3.37 Invalid Credentials

### ISSUE THREAD

**Issue by Boesergolf** [Marginal/EDMarketConnector#403] opened 2019-01-29 08:09 UTC
I am having trouble getting EDMC to run Properly ,
after starting Tce frontiers auth login appears and i login and click approve but edmc then opens and is stuck on Invalidd credentials .
Even tried 3.36 same Problem.

Tried To use Chrome instead of Firefox but even then the Problem stays.
[EDMarketConnector.log](https://github.com/Marginal/EDMarketConnector/files/2806589/EDMarketConnector.log)

**Comment by Marginal** [comment] 2019-01-29 09:36
Run EDMC first, outside of TCE, and complete the login procedure.

**Comment by Boesergolf** [comment] 2019-01-29 14:19
did this already but it doesnt change the invalid credentials even after pressing approve on the fronter auth login

**Comment by jamsoft** [comment] 2019-02-12 18:38
I can confirm this issue.  I'm stuck in the same situation.  I've tried everything I can think of and I'm still getting Invalid Credentials.  I use LastPass so I know whatever is going on it's **not** invalid credentials.

Interestingly I get to the Frontier site, last pass fills the credentials and hitting Login does nothing.

So I restarted everything.

Loaded EDMC which then loaded FireFox.
LastPass entered my credentials 
hitting login pulled up that stupid image Captcha.
I did that, hit submit ... nothing.

I think the issue is on Frontiers ...

**Comment by Marginal** [comment] 2019-02-12 20:11
@jamsoft Please check the Firefox instructions [here](https://github.com/Marginal/EDMarketConnector/wiki/Troubleshooting#app-repeatedly-opens-the-frontier-authentication-website) or try temporarily setting your default browser to something else.

**Comment by Juggernaut93** [comment] 2019-02-12 21:57
@jamsoft I have just had the same issue. I solved by going to the [Frontier auth service website](auth.frontierstore.net), logging in, deauthorizing EDMC and then trying to get credentials again through EDMC. Frontier asked me to authorize EDMC again and then it worked.

**Comment by SHT** [comment] 2019-02-12 22:00
Had the issue for the past 5 minutes, doing exactly what @Juggernaut93 suggested fixed the issue.

**Comment by richardbuckle** [comment] 2019-02-12 22:13
Link should be https://auth.frontierstore.net/

**Comment by Juggernaut93** [comment] 2019-02-12 23:19
@richardbuckle oops, fixed.

**Comment by Marginal** [comment] 2019-02-13 01:53
Thanks. Added to the Troubleshooting guide in 9be34ba.

**Comment by Sobeefy** [comment] 2019-02-13 11:33
I was having the same issue, "invalid credentials" and the frontier auth page being opened, but logging into it did nothing. I attempted Juggernaut93's solution but now my EDMC window is stuck on "Logging in..."

I have spent too much time on this for now so will try again later.

**Comment by SHT** [comment] 2019-02-13 12:24
@Sobeefy try closing ED:MC and any frontier browser tabs. Keep the browser open. Then open ED:MC, it will launch a new tab with the authentication page.

**Comment by jamsoft** [comment] 2019-02-13 14:57
@Marginal I had tried that already.

@Juggernaut93 Will try that solution later, thanks.

**Comment by hack-wizard** [comment] 2019-02-13 17:35
Tried all listed solutions, including clean uninstall and resinstall and now EDMC will not even let me hit update, help please?

**Comment by Marginal** [comment] 2019-02-13 18:10
@hack-wizard https://github.com/Marginal/EDMarketConnector/wiki/Troubleshooting#credentials-settings-are-greyed-out

**Comment by hack-wizard** [comment] 2019-02-13 19:53
I attempted this in both chrome and firefox, same issue with both.

**Comment by Queex** [comment] 2019-02-13 21:07
Same problem here, the deauth workaround fixed it though.

**Comment by hack-wizard** [comment] 2019-02-13 22:34
In case it wasn't clear, I tried the deauth in both Firefox and chrome, when doing a reauth I still get invalid credentials.  Thoughts, ideas or additional steps please?

**Comment by Sobeefy** [comment] 2019-02-14 17:42
Didn't have any luck last night but loaded up tonight, authentication page worked properly and now its fine. Thanks all.

**Comment by Cryzin** [comment] 2019-02-15 04:01
Same issue

**Comment by JasonHutton** [comment] 2019-02-15 04:49
Intermittently same issue.

**Comment by matpoz91** [comment] 2019-02-15 15:54
Same issue here, no workarounds fix it, tried multiple times. Using Chrome, but also checked Opera and Edge

**Comment by Queex** [comment] 2019-02-15 21:30
Now it's stopped working again, only this time it doesn't even pop up the auth window in browser to try to correct it, so there's no possibility of getting it to work.

**Comment by incryptx** [comment] 2019-02-16 16:29
To chime in on users having problems with EDMC/EDDI getting authorized through the browser and with Frontier Authorization API. 

First, go to https://auth.frontierstore.net/ and log in with your "Elite Credential Set" (the same username/password for the Elite Game). Then look at your aurthorized applications. You may also see Inara and EDSM as well as EDMC and EDDI (if you use it). If you cannot get approval for EDMC, then "Deauthorize" EDCM and any other application using an API you may have problems with. Once done, go through the process of authorizing EDMC and if successful, you should now see it in the "Authorized" list again. If EDMC has problems, then the code it gets for authorization is no longer valid or has expired for some reason. This will give you a new code and allow your app to validate again.

Book Mark the site https://auth.frontierstore.net/ so you can use it again in the future. I tried this in Chrome and Firefox. I.E. had problems, but who uses that.

Hope this resolves the issue in the short term until Frontier stabilizes the there API process.

Be well.

**Comment by hack-wizard** [comment] 2019-02-16 16:57
Just tried it again on a lark, seems to be working all of a sudden.  Maybe frontier is doing stuff on their end?

**Comment by matpoz91** [comment] 2019-02-16 17:29
Still not working for me, still tries to log in, still invalid credentials.

**Comment by incryptx** [comment] 2019-02-16 17:43
Did you de-authorize and re-authorize the app with the site I mentioned?

**Comment by matpoz91** [comment] 2019-02-16 17:52
Yes, three times today already, multiple times in the past days. Nothing seems to work for me...

**Comment by Cryzin** [comment] 2019-02-16 20:42
> 
> 
> To chime in on users having problems with EDMC/EDDI getting authorized through the browser and with Frontier Authorization API this process will work.
> 
> First, go to https://auth.frontierstore.net/ and log in with your "Elite Credential Set" (the same username/password for the Elite Game). Then look at your aurthorized applications. You may also see Inara and EDSM as well as EDMC and EDDI (if you use it). If you cannot get approval for EDMC, then "Deauthorize" EDCM and any other application using an API you may have problems with. Once done, go through the process of authorizing EDMC and any other application using an API. When successful, you should now see it in the "Authorized" list again. If EDMC has problems, then the code it gets for authorization is no longer valid or has expired for some reason. This will give you a new code and allow your app to validate again.
> 
> Book Mark the site https://auth.frontierstore.net/ so you can use it again in the future. I tried this in Chrome and Firefox and both work. I.E. had problems, but who uses that.
> 
> Hope this resolves the issue in the short term until Frontier stabilizes the there API process.
> 
> Be well.

This solution worked for me, de-authorize and re-authorizing. Thank you!

**Comment by incryptx** [comment] 2019-02-17 15:56
> Yes, three times today already, multiple times in the past days. Nothing seems to work for me...
> 
> I even reinstalled, still isn't working

That's strange. I assume your using Chrome or Firefox. I also assume your using Windows 7/10?
Is your firewall blocking, or are you trying it through a VPN connection? I tried through a VPN and it never worked. Are you on a corporate network of some kind? Something is blocking you from receiving the incoming dialog back through the browser. I'm sorry, I just don't know enough about your configuration to be of any help. Your not using I.E. or Edge are you?

**Comment by matpoz91** [comment] 2019-02-17 16:24
> That's strange. I assume your using Chrome or Firefox. I also assume your using Windows 7/10?
> Is your firewall blocking, or are you trying it through a VPN connection? I tried through a VPN and it never worked. Are you on a corporate network of some kind? Something is blocking you from receiving the incoming dialog back through the browser. I'm sorry, I just don't know enough about your configuration to be of any help. Your not using I.E. or Edge are you?

- I tried on Chrome, Firefox, Opera and Edge, Chrome being my main browser
- I have Win10
- My firewall isn't blocking, I do not use a VPN, I'm on my own network
- I used EDMC for about a month, it worked perfectly fine until now

Now something about the process:
- I tried deauthing/authing while the game was on and off
- I tried turning the game on first and EDMC later, and also the other way around
- First I deauth and I can auth it without any problems, but the logging in/invalid credentials issue persists
- When it is authorised and I open EDMC, the Frontier Auth page pops up, but when I enter my credentials and click login nothing happens. It still shows on EDMC that it is logging in.
- When I click the update button when it is logging in, Invalid credentials error appears.
- I also tried authenticating by opening EDMC settings and imediatly clicking ok, so the auth page appears. Also didn't work

**Comment by incryptx** [comment] 2019-02-18 15:59
> > That's strange. I assume your using Chrome or Firefox. I also assume your using Windows 7/10?
> > Is your firewall blocking, or are you trying it through a VPN connection? I tried through a VPN and it never worked. Are you on a corporate network of some kind? Something is blocking you from receiving the incoming dialog back through the browser. I'm sorry, I just don't know enough about your configuration to be of any help. Your not using I.E. or Edge are you?
> 
>     * I tried on Chrome, Firefox, Opera and Edge, Chrome being my main browser
> 
>     * I have Win10
> 
>     * My firewall isn't blocking, I do not use a VPN, I'm on my own network
> 
>     * I used EDMC for about a month, it worked perfectly fine until now
> 
> 
> Now something about the process:
> 
>     * I tried deauthing/authing while the game was on and off
> 
>     * I tried turning the game on first and EDMC later, and also the other way around
> 
>     * First I deauth and I can auth it without any problems, but the logging in/invalid credentials issue persists
> 
>     * When it is authorised and I open EDMC, the Frontier Auth page pops up, but when I enter my credentials and click login nothing happens. It still shows on EDMC that it is logging in.
> 
>     * When I click the update button when it is logging in, Invalid credentials error appears.
> 
>     * I also tried authenticating by opening EDMC settings and imediatly clicking ok, so the auth page appears. Also didn't work

I only have a few questions?
1) When you say your on your own network, does that mean you have a router and a set of IP's behind both a firewall and seperate DNS' servers? Or are you on a router straight to the internet? Also, where are you in the world? Are you using some kind of Virtual Network Adapter in Windows 10. I found a TAP-V9 Adapter in my network stack as well as a Hyper-V Adapter. I disabled both so there was just the main "Ethernet Adapter" running.

2) It sounds like something very simple, like a typo in the credential set. Are you cutting and pasting credentials, or doing it from memory? Not to be rude, but I had the same problem for awhile, and then I realized I was hitting zero on my keyboard, right above the "O" I was suppose to use. You also might try changing your password at the Elite Store (where you get the game) and using the new password when you authenticate with EDMC. I did this, and it solved the problem I had with EDDI's use of Frontier's API, while EDCM continued to work, when EDDI would not.

The problems you are having make no sense here. It should work, but something weird is going on. A network switch in the way, a typo, a set of credentials that don't match, something unseen or unrealized. Best I can do for you sir. That's all I can suggest. 

Hope this gives you some things to try. Maybe you will discover what the problem is.

Be well.

**Comment by matpoz91** [comment] 2019-02-18 19:27
I've managed to find a solution.

It appears that on my browsers, during the authorisation when the window that wants to open EDMC appears, I clicked to always open such links in EDMC. I've installed another browser and didn't tick that checkbox this time... and it worked. Authorised, logged in, everything works great. I don't know what was the real problem here, but leaving this solution just in case.

**Comment by richardbuckle** [comment] 2019-02-18 19:31
That makes perfect sense. EDMC registers itself as the handler for a custom URL protocol, which the authorisation page invokes as a callback so as to return data to EDMC. For security reasons the browser needs a human to confirm that EDMC is the proper handler for that protocol.

**Comment by matpoz91** [comment] 2019-02-18 19:40
> For security reasons the browser needs a human to confirm that EDMC is the proper handler for that protocol.

So why does the browser add the chceckbox to handle it automatically in the first place? That's like asking for something to go wrong. And also, is there any method to "uncheck" the checkbox now on my default browser? I've deleted the cookies and restored page notification defaults, but no luck.

**Comment by incryptx** [comment] 2019-02-18 22:23
> > For security reasons the browser needs a human to confirm that EDMC is the proper handler for that protocol.
> 
> So why does the browser add the chceckbox to handle it automatically in the first place? That's like asking for something to go wrong. And also, is there any method to "uncheck" the checkbox now on my default browser? I've deleted the cookies and restored page notification defaults, but no luck.

Most browsers do. It's under "Applications" in Firefox. Let me get out of Linux right now and I will post what you need to add for the application to succeed.

I'm glad you worked it out. I thought it would be something weird like that.

Good deal. You now have two solutions next time it occurs.

**Comment by DreamlnCode** [comment] 2019-02-19 01:39
De-authorising then Re-Authorising worked for me when I ran into this problem today.

**Comment by Marginal** [comment] 2019-02-19 02:59
I can't reproduce the problem when setting Chrome to always open EDMC links with EDMC, but it's a [known](https://github.com/Marginal/EDMarketConnector/wiki/Troubleshooting#app-repeatedly-opens-the-frontier-authentication-website) problem in Firefox.

In any case this should be fixed in the next release.

**Comment by DreamlnCode** [comment] 2019-02-19 18:02
I'll also add that the the browser with the problem was indeed Firefox.

**Comment by Marginal** [comment] 2019-02-19 18:52
The Firefox issue is fixed in [Release 3.38](https://github.com/Marginal/EDMarketConnector/releases/latest) and the deauthorization problem gives a [different error message](https://github.com/Marginal/EDMarketConnector/wiki/Troubleshooting#error-an-error-occured) (not particularly helpful but that's what the server reports).
So marking this fixed. Please raise a new issue for any remaining problems.

**Closed by Marginal** 2019-02-19 18:52 UTC
