### ISSUE TITLE
Error: Server is down

### ISSUE THREAD

**Issue by tententacles** [Marginal/EDMarketConnector#47] opened 2015-12-15 23:15 UTC
I'm currently getting Error: Server is down. Everything was working fine before the Horizons launch today. Since Horizons has launch, I'v been receiving this error. The Elite: Dangerous servers are up, so I'm not sure which server it's talking about.

**Comment by Marginal** [comment] 2015-12-15 23:51
Duplicate of #46

**Closed by Marginal** 2015-12-15 23:51 UTC
Labels: duplicate
