### ISSUE TITLE
Login credential stored in plain text

### ISSUE THREAD

**Issue by neotron** [Marginal/EDMarketConnector#176] opened 2017-01-26 06:29 UTC
![capture](https://cloud.githubusercontent.com/assets/20304/22322012/e945a4fe-e34d-11e6-9db5-4342afa0eaa3.PNG)

EDMC stores both login and password in plain text. Registry on windows, NSUserDefaults on Windows and from what I can see a simple text file on Linux.

This is bad practice and can lead to account information being compromised.

**Comment by PacoHobi** [comment] 2017-01-26 08:35
Interesting problem. Just for my understanding, as I don't know: how would one securely store the password locally? EDMC has to somehow be able to get the password in plain text, and anybody could check the source code to see how EDMC goes from the "secure stored password" to the plain text password, right?

**Comment by DrFreez** [comment] 2017-01-26 08:52
OpenID or OAuth

**Comment by faybs** [comment] 2017-01-26 08:56
In windows, use CryptProtectData and CryptUnprotectData, passing 0 for the flags. That will take a buffer and encrypt/decrypt it using the current user's credentials. https://msdn.microsoft.com/en-us/library/windows/desktop/aa380261(v=vs.85).aspx

**Comment by razvanilin** [comment] 2017-01-26 08:57
OpenID and OAuth requires you to be connected to the internet. Not familiar with this tool, but from my understanding it is designed to also work offline

**Comment by neotron** [comment] 2017-01-26 08:59
On MacOS you can use the keychain to store it.

**Comment by neotron** [comment] 2017-01-26 08:59
Also the login here is used to access the Elite mobile app API to get market data. Need to be online to do that.

**Comment by DrFreez** [comment] 2017-01-26 09:03
@razvanilin 
> Not familiar with this tool
Seriously? In 2017? Google, Twitter, Facebook, etc. all have OAuth.

**Comment by razvanilin** [comment] 2017-01-26 09:07
@DrFreez I was referring to EDMarketConnector... I thought that this tool is designed to work offline too which means OAuth is not the best choice.

And believe me, I know what OAuth is.

**Comment by faybs** [comment] 2017-01-26 09:07
OAuth is kinda overkill though, and it requires that you have an account with an OAuth provider (so in order to use EDMC you'd need to first log on to Facebook or Google)

**Comment by DrFreez** [comment] 2017-01-26 09:16
@razvanilin not use OAuth for enter in app. Work in offline, but before send data get auth\API key over OAuth.

**Comment by DrFreez** [comment] 2017-01-26 09:20
@EDMC OAuth it's not monopoly. EDMC must have OAuth interface, not need use OAuth interface Facebook or Google. facepalm.jpg

**Comment by Marginal** [comment] 2017-01-26 09:26
The FDev server doesn't offer an OAuth interface, so that isn't an option.

Duplicate of #89

**Closed by Marginal** 2017-01-26 09:26 UTC

**Comment by SimonSchick** [comment] 2017-01-26 16:38
You could at least encrypt the password with a platform dependant key, better than nothing...

**Comment by lausianne** [comment] 2017-03-13 19:32
I learned about this only now and immediately deleted the PW from the registry. Has this been fixed meanwhile? Anytime soon?

**Comment by Marginal** [comment] 2017-03-13 23:39
v2.26 and later of EDMC store the password in the Windows Credential Vault / macOS Keychain instead of the registry / preferences.
