### ISSUE TITLE
displays "Inara - Cannot login !" message

### ISSUE THREAD

**Issue by Dreibuchstaben** [Marginal/EDMarketConnector#270] opened 2017-11-26 18:17 UTC
HI,

it is connected with correct Inara API key and updates the status there. The Inara login status of ED MC must be wrong.

I use the right now installed version of plugin and ED MC

**Comment by Marginal** [comment] 2017-11-26 20:46
Duplicate of #262

**Closed by Marginal** 2017-11-26 20:46 UTC
Labels: duplicate
