### ISSUE TITLE
Using EDMC Reduced Rares profits?

### ISSUE THREAD

**Issue by Red13x3** [Marginal/EDMarketConnector#171] opened 2017-01-10 13:22 UTC
Is anyone aware of this one?

Apparently if you have EDMC running when you pull into a station to sell a Rare, the value you will get for it is way less than if you are NOT running EDMC.

Have not confirmed this myself - Just seen it posted on a FB group.

**Comment by Marginal** [comment] 2017-01-10 21:57
See https://github.com/Marginal/EDMarketConnector/wiki/Troubleshooting#rares-profits-wiped-out

Duplicate of #92.

**Closed by Marginal** 2017-01-10 21:57 UTC

**Comment by Red13x3** [comment] 2017-01-11 20:43
Has this been investigated before closing it?

--
Mark
iPhone: 0402 322 901

**Comment by Marginal** [comment] 2017-01-11 23:40
Yes.

**Comment by Red13x3** [comment] 2017-01-12 12:56
And what was the findings? Does it affect Rares profits or not? Because if it doesn't, then I want to slap the person that's spreading false rumors. 

--
Mark
iPhone: 0402 322 901

**Comment by 7h3ju57** [comment] 2017-01-12 13:21
This has already been answered above. And it's in the wiki.
