### ISSUE TITLE
Can't see commodities market at some Outposts - "Error: Can't get market data!"

### ISSUE THREAD

**Issue by lemmy04** [Marginal/EDMarketConnector#6] opened 2015-06-13 10:18 UTC
I'm trying to send market prices to eddn, but the app says "Station has no marketplace"... while I'm docked and am looking at commodity prices, no less.

**Comment by Marginal** [comment] 2015-06-13 11:22
Which system / station ?

**Comment by lemmy04** [comment] 2015-06-13 12:23
Marlowe Colony, system HIP 68522.

Tried both the latest official release of EDMarketConnector and the new 1.40 RC1, same result.

**Comment by AnthorNet** [comment] 2015-06-13 13:00
It happens to me too, since 1.3.2...
Will try to go elsewhere, I haven't change station since update + 30 minutes, 
and the servers may have not been synced.

**Comment by Marginal** [comment] 2015-06-13 15:03
I have seen this once in the past. I'll investigate.

**Comment by Marginal** [comment] 2015-06-14 00:28
Yep HIP 68522 / Marlowe Colony is broken for me too.
Closing this as wonfix, but it's more like "Can't fix".

**Comment by Marginal** [comment] 2015-06-14 17:43
Pandinus / Bulychev Mines has the same issue.
The iOS Companion app doesn't display the market either.

**Comment by lemmy04** [comment] 2015-06-18 15:10
maybe it's all stations that are new in 1.3?

**Comment by AnthorNet** [comment] 2015-06-18 16:08
@lemmy04 Nop, can confirm the station I was worked before the update, and not after !

**Comment by Estomes** [comment] 2015-06-24 09:12
Hello All,

there is another Outpost:
Chiang Landing in VotadJa - Industrial Outpost!

**Comment by Marginal** [comment] 2015-06-25 18:14
On the other hand:
San Neb Xoc / Flade Dock
works OK today, and is an Industrial Outpost.

**Comment by rcthelp** [comment] 2015-07-08 18:25
Are you collecting outposts with this problem?

CAHUILE/Judson Installation

**Comment by Marginal** [comment] 2015-07-08 18:32
@rcthelp 
Thanks. Another Industrial Outpost.

**Comment by hmage** [comment] 2015-07-31 21:25
Kuruntabal // Van Houten Survey

Says "Station doesn't have anything!", though.

Did the connector's message change since opening of this issue?

**Comment by Marginal** [comment] 2015-07-31 22:28
> Says "Station doesn't have anything!", though.
> Did the connector's message change since opening of this issue?

Yes. You now get this message if you have selected EDDN output and the station has neither a commodity market nor a shipyard.

**Comment by vakius** [comment] 2015-09-11 09:05
Same issue for Dakshu: Rubruck Dock 
Refinery outpost.

**Comment by QuackingPlums** [comment] 2015-09-16 00:02
Well, someone had to go check: Hutton Orbital is also reported as having no market. ;-)

**Comment by Marginal** [comment] 2015-09-16 04:21
> Hutton Orbital is also reported as having no market.
That **is** a shame.
(And another Industrial Outpost).

**Comment by RatSalad59** [comment] 2015-09-26 16:41
Same issue at Beta Gruis, Boyajian Mines

**Comment by CraigYorke** [comment] 2015-09-27 17:19
Also Muras, Glazkov mine

**Comment by CraigYorke** [comment] 2015-10-02 00:27
Sheroo, Schirra Mines has a market

**Comment by Mikayex** [comment] 2015-10-04 11:23
Problem confirmed on HR 8352/Ziewe Landing (industrial outpost)

**Comment by EntropicLiquid** [comment] 2015-10-11 19:13
Issue confirmed at LHS 1887 - Clare Terminal (military outpost).

I used EliteOCR to get the commodity data uploaded to EDDN in the end.

**Comment by Freudlund** [comment] 2015-10-13 19:52
Issue confiormed, Mpalouros, Scott Point, Industrial outpost, EliteOCR fixed it

**Comment by rcthelp** [comment] 2015-10-23 17:53
KOLABINATES/Grant Plant is another. Outpost with Refinery Economy.

Data updated with upload to Maddavo.

**Comment by mEDI-S** [comment] 2015-10-28 03:32
Hi,

same problem in:
LHS 3385, Rasch Plant https://ross.eddb.io/station/update/2618
LHS 3385, Scalzi Station https://ross.eddb.io/station/update/1597

i think all sations, the notting sell and only buy have the same problem and this is a extrem big problem

i found 3096 stations in my local db with data > 200 days the notting sell and never get updates

mEDI

**Comment by Marginal** [comment] 2015-10-28 03:55
> this is a extrem big problem
I agree that it's a problem, but I can't do anything about it.
~3,000 stations out of ~40,000 isn't too bad.

**Comment by mEDI-S** [comment] 2015-10-28 04:02
21k sell notting 3k from the have the last 200 days no update

bug report as ios app user? ;)

**Comment by repaxan** [comment] 2015-10-28 04:04
Wolf 315, Russ Platform

**Comment by Marginal** [comment] 2015-10-28 04:08
> bug report as ios app user? ;)

You're welcome to try.
FYI the official app crashes on iOS 9 - bug report [here](https://forums.frontier.co.uk/showthread.php?t=188886).

**Comment by mEDI-S** [comment] 2015-10-29 10:38
i open a new bug report and hope the best

https://forums.frontier.co.uk/showthread.php?t=195774&p=3019500#post3019500

**Comment by intel352** [comment] 2015-10-30 03:26
Found another bad station:

Ch'i Ling, McMillan Platform - https://ross.eddb.io/station/update/9841
It's a mining outpost, has commodities. Says "Station doesn't have anything!", so it won't update the commodities.

I'm wondering if the apostrophe is interfering.

Using latest release on ED 1.4.01 - Win10

**Comment by intel352** [comment] 2015-10-30 05:51
Here's another:

Lei Cherna, Mukai Dock - https://ross.eddb.io/station/update/9536
Again a mining outpost, has commodities, and wrongly says station doesn't have anything.

**Comment by intel352** [comment] 2015-11-02 07:19
Another station:

Xuangeriva, Bond Prospect - https://eddb.io/station/4796
Again, mining outpost.

**Comment by mEDI-S** [comment] 2015-11-02 15:06
send please the stations to this thread too
https://forums.frontier.co.uk/showthread.php?t=195774&p=3019500#post3019500

and bump the report!
this is a EDAPI bug and not a EDMC bug
and they are only fixed when it is recognized as a major problem

**Comment by repaxan** [comment] 2015-11-08 02:33
https://eddb.io/station/32918

**Comment by nickfromkew** [comment] 2015-11-25 02:25
Just found this one with the same issue: 
https://eddb.io/station/27664 
Komarov Hub at Rhibonii

**Comment by Hansfranz1337** [comment] 2015-12-02 12:25
Same issue with : 
https://eddb.io/station/24991
Fallows Hub in Tai Shere

**Comment by Zippovich** [comment] 2015-12-23 21:06
https://eddb.io/station/26223 - same issue (win 7, v.2.0.1.0)

**Comment by liukang168** [comment] 2015-12-24 18:42
HIP 95677 / Maclaurin Installation (Planetary Port) 

Outfiiting is working, but not the commodities ..

**Comment by Mathajas** [comment] 2015-12-25 10:48
HIP 110028,Zander Dock

Error: Can't get market data!

commodities is working

**Comment by Aexrael** [comment] 2015-12-27 15:07
Another one for the list.

https://eddb.io/station/11935

**Comment by LabGecko** [comment] 2015-12-27 23:02
Another for the list: Vinge Dock in Olkondi
Returns "Can't get market data", but got that error while staring at the Commodities window.

**Comment by zigarot** [comment] 2015-12-28 13:17
https://eddb.io/station/9874
getting this error here.
Mitl - Bethe Station

**Comment by rcthelp** [comment] 2015-12-28 20:03
The author of this application cannot do anything to fix this problem, which lies with the Frontier server.  If you ran the official Frontier Companion app on these stations you would find that it also thinks there are no commodity markets at these stations.

Perhaps you call all add stations/outposts as you find them to this bug report on Frontier forums, instead of here.

https://forums.frontier.co.uk/showthread.php?t=217169

**Comment by Mathajas** [comment] 2015-12-29 17:06
"Can't get market data"
Mayor Terminal  Hercuni

https://eddb.io/station/15562

**Comment by KnightDemons** [comment] 2016-01-03 10:19
"Error: Can't get market data!" 
HIP 115937 - Wheeler's Exile
https://eddb.io/station/1418

**Comment by Kixel** [comment] 2016-01-06 20:23
"Error: Can't get market data!"
Wongkamala - Stromgren mines    (Extraction/Refinery)

**Comment by georgehank** [comment] 2016-01-07 10:23
Same error (first time I've encountered it) in Niu Bese / Krikalev station.

I don't know any of the other systems with broken stations, but Niu Bese is a weird one: it has no planets according to System Map, but it does have a smallish rock near this station (*not* on the System Map) with a Haz RES.  And near this station there *is* a planet which doesn't show on the Map.  The planet (or moon?) also doesn't have a name.

**Comment by CraigYorke** [comment] 2016-01-07 13:01
Hi all,

Why am I being cc'd on all these ED Market Connector emails? I have 
nothing to do with this program other than having supplied data at one 
point in the past.

Craig



On 06/01/2016 4:23 PM, Kixel wrote:
>
> "Error: Can't get market data!"
> Wongkamala - Stromgren mines (Extraction/Refinery)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Marginal/EDMarketConnector/issues/6#issuecomment-169450580>.
>

-- 
Craig Yorke
President
Image House Digital Incorporated
5729 McCully Street, Halifax, Nova Scotia, Canada
B3K 1R4
1-902-482-1823

**Comment by Marginal** [comment] 2016-01-07 18:41
> Why am I being cc'd on all these ED Market Connector emails?

Because at some point you decided that you wanted to be. To unsubscribe [click here](https://github.com/Marginal/EDMarketConnector/subscription) and choose "Ignore".

**Comment by CraigYorke** [comment] 2016-01-07 19:05
Jonathan,

Thank you for your reply. I have done as you suggested but note that I 
was set up as "not watching" which GitHub says means that I should only 
have received emails when my name was involved.

Craig



On 07/01/2016 2:42 PM, Jonathan Harris wrote:
>
>     Why am I being cc'd on all these ED Market Connector emails?
>
> Because at some point you decided that you wanted to be. To 
> unsubscribe click here 
> <https://github.com/Marginal/EDMarketConnector/subscription> and 
> choose "Ignore".
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Marginal/EDMarketConnector/issues/6#issuecomment-169768850>.
>

-- 
Craig Yorke
President
Image House Digital Incorporated
5729 McCully Street, Halifax, Nova Scotia, Canada
B3K 1R4
1-902-482-1823

**Comment by Marginal** [comment] 2016-01-07 19:10
> but note that I was set up as "not watching" which GitHub says means that I should only have received emails when my name was involved.

Your name *is* involved - you [posted](https://github.com/Marginal/EDMarketConnector/issues/6#issuecomment-143578115) in this issue.

**Comment by LabGecko** [comment] 2016-01-09 20:07
I got the same issue. Posted an error once, have been receiving each
    comment since. I am set to "Not Watching", which reads
    "You will only receive notifications when you participate or are
    @mentioned."
    "Watching" reads "You will receive all notifications for this
    repository."
    You should boldface the 'when you participate' portion. To me, at
    least, it seems counter-intuitive to be automatically put on 'Watch'
    status because you commented once. Or better yet, fix the script so
    people choose when they get all notifications, even if they decide
    to help. Note that I probably won't even see a response to this
    letter since my only available resolution was to set this to Ignore.
    All or Nothing is not very useful.
    
    On 1/7/2016 1:10 PM, Jonathan Harris
      wrote:
    
    
      
        but note that I was set up as "not watching" which GitHub
          says means that I should only have received emails when my
          name was involved.
      
      Your name is involved - you posted
        in this issue.
      —
    
    
  



	
		
			
				
			
		
		
			
				This email has been checked for viruses by Avast antivirus software.
				www.avast.com

**Comment by comandantevogan** [comment] 2016-01-27 23:31
"Error: Can't get market data!" 
HALE CAMP / MELINGOI

**Comment by LynxChaus** [comment] 2016-02-09 13:52
Maybe change error message to "Server not provided market data. Report this error to https://forums.frontier.co.uk/showthread.php?t=195774" ?
And push some status to EDDB for record this broken station?

**Comment by AusMatt** [comment] 2016-03-31 00:03
This station too: [Vonnegut Beacon @ Arikaras](https://eddb.io/station/23101)
Yes it does have a working commodities market but no shipyard or outfitting.

**Comment by Marginal** [comment] 2016-07-14 02:31
This issue appears fixed in E:D 2.1 so closing.

**Closed by Marginal** 2016-07-14 02:31 UTC
Labels: FDev API
