### ISSUE TITLE
Made the mistake of updating EDMC, "invalid credentials" now

### ISSUE THREAD

**Issue by d4eaming** [Marginal/EDMarketConnector#241] opened 2017-09-26 20:11 UTC
EDMC has been working perfectly for weeks since I originally installed it. I can see the updates every single time I dock when I use the market resources, and in fact I have relied on this program for my trading runs exclusively, since it updates as I make my loops.

But not any more! I thought since the game just updated that I should see if there's an update for EDMC. Now I can't log in. There's no verification, I can't tell if it's actually doing anything, it just immediately says "invalid credentials". I've logged out of the ED launcher, I've made sure the launcher AND the game are closed. I've logged in and out specifically to make sure my password was correct on the launcher, the forums, the Frontier Store (it was), and absolutely nothing happens. Nothing at all.

At this point since I rely on it so heavily that I regret updating it and I am very upset that nothing I do will make it work and now I have nothing to rely on if no one else is using my routes and the tool where I need updated information.

What could possibly cause the problem of no longer being able to log in just because I updated the EDMC? That makes zero sense.

I have also whitellisted it with my antivirus software and added it to the firewall white list. Still nothing.

I hope this can get fixed soon because I also use EDSM, and this is the best way for me to make sure that stays updated, too.

**Comment by D1G1TALBOY** [comment] 2017-09-26 20:29
Same here, but I'll expect it to get patched soon hopefully.

**Comment by inorton** [comment] 2017-09-27 07:17
Hiya, the servers at FD that provide the core data  (the companion api server) is currently down, so until FD fix that you wont be able to get EDMC to "login".   Things like the EDSM plugin should actually still continue to submit data to EDSM though when you jump or scan.

**Comment by inorton** [comment] 2017-09-27 07:19
Duplicate of #242

**Closed** 2017-09-27 14:40 UTC
Labels: duplicate
