### ISSUE TITLE
ERROR: Frontier Server is down

### ISSUE THREAD

**Issue by STKDirty** [Marginal/EDMarketConnector#364] opened 2018-12-14 04:16 UTC
This is happening since the 3.3 update to ED.  It seems like it may still be working, but this message comes up every time I start EDMC.  Log attached.

o7
STKDirty
[EDMarketConnector.log](https://github.com/Marginal/EDMarketConnector/files/2678624/EDMarketConnector.log)

**Comment by Count0Int** [comment] 2018-12-14 04:57
I am getting the same error.  Log attached.
[EDMarketConnector.log](https://github.com/Marginal/EDMarketConnector/files/2678702/EDMarketConnector.log)

**Comment by AnthorNet** [comment] 2018-12-14 04:58
Hi we are aware of that error, and we just need to be patient, this is not something on our hand right now :)

Thanks

**Comment by STKDirty** [comment] 2018-12-14 05:19
Thanks!  No rush, just wanted to make sure you were aware.

o7
Dirty

**Comment by Gconnor** [comment] 2018-12-15 02:43
> 
> 
> Hi we are aware of that error, and we just need to be patient, this is not something on our hand right now :)
> 
> Thanks

Any idea what (if any) functionality this affects? Thanks!

**Comment by AnthorNet** [comment] 2018-12-15 06:03
Hi, this should only affect market, dhipyard, and outfitting data updates.

**Comment by AnthorNet** [comment] 2018-12-15 06:04
If you use EDSM under your account, EDDN updater is a temporary fix we have put in place.

**Comment by Praetorian86** [comment] 2018-12-15 11:45
Is the problem solvable from your side, or Frontier screwed something up so we need to wait for them?

**Comment by JPVenson** [comment] 2018-12-17 20:16
What do you mean by "EDDN updater is a temporary fix" is there any action required by the user?

**Comment by JPVenson** [comment] 2018-12-17 21:19
I am afraid i dont get it, under the EDSM FAQs there are only 3 updaters listed
![image](https://user-images.githubusercontent.com/6794763/50116133-9825e800-0249-11e9-897e-dc7ece3994b6.png)
Including this tool. Both other tools do not list the functionality of uploading market data.

Could you keep it simple and post me a link to the tool you mean? :-D

**Comment by AnthorNet** [comment] 2018-12-17 21:21
In the account menu, in the top navigation bar, the one with the avatar, click on EDDN updater.

**Comment by Gavote** [comment] 2018-12-18 15:15
> I am afraid i dont get it, under the EDSM FAQs there are only 3 updaters listed
> ![image](https://user-images.githubusercontent.com/6794763/50116133-9825e800-0249-11e9-897e-dc7ece3994b6.png)
> Including this tool. Both other tools do not list the functionality of uploading market data.
> 
> Could you keep it simple and post me a link to the tool you mean? :-D

Step one: make sure you have an account on EDSM
Step two: log in
Step three: click on your profile button in the top bar (second button from the right edge)
Step four: click on EDDN updater in the drop down menu
Step five: follow the directions on the resulting page.

**Comment by Praetorian86** [comment] 2018-12-18 15:36
It might be a known thing, but upon doing a "brute force update" (downloading the content of the git repo, and copying it over the installed 3.2.0.0 release, overwriting everything), EDMC started working again partially. EDDB ROSS logs says the commodity update ended up with errors, but upon refreshing the EDDB page, it shown valid data, and the "last update" jumped from days to 10something seconds. I've said partially, because it's not always updating. (Been doing mutiple supply quests for the same goods, so I docked to the same station quite a few times, and checked if stuff got updated after opening the market or not)

**Comment by luzclasil** [comment] 2018-12-18 16:00
> In the account menu, in the top navigation bar, the one with the avatar, click on EDDN updater.

Do I need to do that every time I dock or can I just go there once or twice every few hours of gameplay?

**Comment by JPVenson** [comment] 2018-12-18 17:34
@luzclasil you can start the timer and let it run ... you should turn it off when leaving the game but it should run in background

![image](https://user-images.githubusercontent.com/6794763/50171734-89940b00-02f3-11e9-8154-bd77fa256121.png)

I am currently not even in the game

![image](https://user-images.githubusercontent.com/6794763/50171769-9a448100-02f3-11e9-9d2e-eca79df0acdb.png)

**Comment by luzclasil** [comment] 2018-12-18 17:44
> @luzclasil you can start the timer and let it run ... you should turn it off when leaving the game but it should run in background
> 
> ![image](https://user-images.githubusercontent.com/6794763/50171734-89940b00-02f3-11e9-8154-bd77fa256121.png)
> 
> I am currently not even in the game
> 
> ![image](https://user-images.githubusercontent.com/6794763/50171769-9a448100-02f3-11e9-9d2e-eca79df0acdb.png)

Will do that!
 I've noticed it only refreshes every 2 min and only if the player is docked. What if I dock/undock in like 30s, won't it be updated then? 
Thanks and I'm sorry for that many question, have just started contributing to our community and now the program is no longer function properly so it's a bit too much for me to swallow at once.
Thanks!

**Comment by JPVenson** [comment] 2018-12-18 18:31
@luzclasil if you dock/undock within the 2 minutes nothing will happen. 

You are very welcome. as you can read i had some trouble myself ;-)

**Comment by Sharlikran** [comment] 2018-12-19 03:07
To tie things together for those trying to search comments this is being discussed in other places as well. #366 and in #315.

**Comment by CurePindal** [comment] 2018-12-20 13:51
> 
> 
> If you use EDSM under your account, EDDN updater is a temporary fix we have put in place.

Sorry, but I still dont understand what that means or how to use that temp fix as workaround!? New to this stuff... =/

**Comment by Praetorian86** [comment] 2018-12-20 14:17
> > If you use EDSM under your account, EDDN updater is a temporary fix we have put in place.
> 
> Sorry, but I still dont understand what that means or how to use that temp fix as workaround!? New to this stuff... =/

Check [this]https://github.com/Marginal/EDMarketConnector/issues/364#issuecomment-448254849(url) comment.

**Comment by JPVenson** [comment] 2018-12-20 17:23
@CurePindal You can start the the "EDDN Updater" and fly around. The Webseite is connected to your Frontier Account and will pull every 180 sec the current station you have docked. If you are docked while the updater gets this data, the EDDN Updater will have all infos about that Station including the Market Prices in this station.

**Comment by a12d** [comment] 2018-12-21 14:40
I looked around so see it there was a bug report to FDev and found https://forums.frontier.co.uk/showthread.php/465601-New-API-authentication-now-stopping-3rd-party-EliteG19s-amp-EDMC-authentication?highlight=api

It might be worth updating this bug and hopefully FDev will look at the issue

**Comment by Marginal** [comment] 2018-12-21 16:53
Duplicate of #359

**Closed by Marginal** 2018-12-21 16:53 UTC
Labels: FDev API

**Comment by henryfoster** [comment] 2018-12-24 14:36
Does it still load the data to EDDB and so on or is it worthless untill the Frontierserver error is fixed?
