### ISSUE TITLE
"Station doesn't have anything!"

### ISSUE THREAD

**Issue by EValve1** [Marginal/EDMarketConnector#34] opened 2015-11-02 05:13 UTC
Hey there! I've recently started using this to help update market info :), only have come across a problem!

Arrived at HIP12167 Tikhonravov Port, clicked update aaand : "Station doesn't have anything!" string pops up.

The station does appear on EDDB.io, has a commodity market and seems to have received it's last update 20 days ago!

Hoped you could help me clarify and maybe help me out on resolving this!

~EValve

**Comment by Marginal** [comment] 2015-11-02 05:26
This is a duplicate of #6

**Closed by Marginal** 2015-11-02 05:26 UTC
Labels: duplicate
