### ISSUE TITLE
"Invalid Credentials" after a clear save with SAME name on PC

### ISSUE THREAD

**Issue by ciuccia** [Marginal/EDMarketConnector#160] opened 2016-11-19 16:54 UTC
After i wiped my save game for a fresh restart, i can't use anymore EDMC...
It's now some days i get "Invalid Credentials" error when trying to update.
I used the **same** name as before on the new save.
Everything is setup correctly on ESDM and EDDN.

Is there a way to fix this? I'm constantly getting the old savegame data.
I've tried deleting cookies.txt too and re-verified with the email-sent code... but nothing happens, same old data retrieved!

**Comment by Marginal** [comment] 2016-11-19 17:47
Duplicate of #157

**Closed by Marginal** 2016-11-19 17:47 UTC
Labels: duplicate
