### ISSUE TITLE
sometimes no shipyard data reported ?

### ISSUE THREAD

**Issue by Duke-Jones** [Marginal/EDMarketConnector#110] opened 2016-05-11 13:44 UTC
Hi Jonathan,

I'm the developer of ED-IBE and have also integrated a companion interface.
I ascertain that it is possible sometimes to get no shipyard info even if the station has a shipyard. 
All other data is transmitted everytime (commander/lastSystem/lastStarport/commodities/modules and so on)
Often on next call to the FD servers the shipyard info is transmitted after all.

Do you have ascertain the same behaviour with EDMC ?

**Comment by Marginal** [comment] 2016-05-11 14:09
Yes, it's a known bug, but it looks like I haven't documented it. I think it occurs when the server load is high. 

In the GUI app I try to [work round](https://github.com/Marginal/EDMarketConnector/blob/master/EDMarketConnector.py#L457) this by silently retrying the API again after 5 seconds if eddb's station database says that the station should have a shipyard. This works more often than not. But visiting the shipyard in-game seems to be the only way to force the API to return shipyard data.

I've added a [note](https://github.com/Marginal/EDMarketConnector/wiki/Troubleshooting#shipyard-data-not-reported) to the wiki).

**Comment by Marginal** [comment] 2016-05-11 14:14
Actually I forgot that I also silently [retry](https://github.com/Marginal/EDMarketConnector/blob/master/EDMC.py#L131) the API after 5 seconds in the command-line program as well.

**Comment by Marginal** [comment] 2016-05-11 14:23
And another thing! [Here's](https://github.com/Marginal/EDMarketConnector/issues?q=label%3A"FDev+API") a bunch of other issues you should look out for in your Companion API interface.

**Comment by Marginal** [comment] 2016-05-11 14:26
Duplicate of #86.

**Comment by Duke-Jones** [comment] 2016-05-11 14:28
Ok, thank you for the infos.
I will have an eye on the awaited issues.

**Closed** 2016-05-24 17:49 UTC
Labels: duplicate, FDev API
