### ISSUE TITLE
Error when writing ship loadout file with special characters

### ISSUE THREAD

**Issue by Uriei** [Marginal/EDMarketConnector#310] opened 2018-04-02 15:22 UTC
My current ship is called "Dude, where's my ship?" and I get this.

![image](https://user-images.githubusercontent.com/6078221/38201952-5c1fb956-369a-11e8-8c3b-c9d1541d61d0.png)

**Comment by Marginal** [comment] 2018-04-03 00:37
Duplicate of #303. Will be fixed in the next release.

**Closed by Marginal** 2018-04-03 00:37 UTC
