### ISSUE TITLE
Engineering wont export to coriolis

### ISSUE THREAD

**Issue by Pendragon55555** [Marginal/EDMarketConnector#250] opened 2017-10-11 00:03 UTC
Whenever I try to export my ships fit to coriolis.edcd.io the engineered modules and rolls are not transferred while they are transferred to www.edshipyard.com

**Comment by willyb321** [comment] 2017-10-11 04:01
See https://github.com/EDCD/coriolis/issues/158#issuecomment-335675734

**Comment by strideynet** [comment] 2017-10-12 08:01
Duplicate Issue.

**Comment by Marginal** [comment] 2017-10-12 09:31
Duplicate of #246

**Closed by Marginal** 2017-10-12 09:31 UTC
