### ISSUE TITLE
'capacity' appears on bottom left of form after update button pressed

### ISSUE THREAD

**Issue by fusion-reactor** [Marginal/EDMarketConnector#54] opened 2015-12-21 18:15 UTC
[EDMCFail.docx](https://github.com/Marginal/EDMarketConnector/files/68823/EDMCFail.docx)
After clicking Update button, message "Fetching data" briefly appears to be replaced with 'capacity' message.  Tried re-installing but no change.

**Comment by Marginal** [comment] 2015-12-21 18:22
Duplicate of #51.

**Closed by Marginal** 2015-12-21 18:22 UTC
