### ISSUE TITLE
EDMC Always Adds VerboseLoging entry.

### ISSUE THREAD

**Issue by MarkAusten** [Marginal/EDMarketConnector#137] opened 2016-08-18 06:42 UTC
Every time EDMC is started it adds a new VerboseLogging="1" entry to the AppConfigLocal.xml file. Open and close EDMC 5 time and you will see at least 5 copies of the VerboseLoging attribute which invalidates the xml. Some third party applications throw an exception on trying to open the config file.

I am a programmer but Python is not one of the languages I use, however, in monitor.py in the enable_logging_in_file function definition, the writing of the VerboseLogging attribute on lines 107 and 111 should only occur if the attribute does not exist. Therefore I suggest calling the logging_in_enabled_in_file function in an if statement starting at line 103, the line before "with open(appconf, 'wt') as f:" and enclosing everything after that up to but not including the return statement on line 116 like this:

```
if not self.logging_enabled_in_file(appconf)
    with open(appconf, 'wt') as f:
        start = content.lower().find('<network')
        if start >= 0:
            f.write(content[:start+8] + '\n\t\tVerboseLogging="1"' + content[start+8:])
        else:
            start = content.lower().find("</appconfig>")
            if start >= 0:
                f.write(content[:start] + '\t<Network\n\t\tVerboseLogging="1"\n\t>\n\t</Network>\n' + content[start:])
            else:
                f.write(content)	# eh ?
                return False
```

I think that this should solve the problem.

There may be a better way to to do this, as I say I'm not a Python programmer.

**Comment by Marginal** [comment] 2016-08-18 10:22
Duplicate of #133

**Closed by Marginal** 2016-08-18 10:22 UTC
