### ISSUE TITLE
Not showing enginered parts

### ISSUE THREAD

**Issue by RexTheCapt** [Marginal/EDMarketConnector#227] opened 2017-07-15 02:40 UTC
Before i updated the program i could see engineered modules but i cant do it now.

**Comment by Marginal** [comment] 2017-07-15 09:33
This is a [known defect](https://forums.frontier.co.uk/showthread.php/342408) in Frontier's servers, introduced in E:D 2.3. Feel free to pile in on that thread.

Duplicate of #191

**Closed by Marginal** 2017-07-15 09:33 UTC
Labels: duplicate, FDev API
