### ISSUE TITLE
Causes microstuttering

### ISSUE THREAD

**Issue by bathrobehero** [Marginal/EDMarketConnector#141] opened 2016-09-05 13:43 UTC
Whenever I have EDMC open (even if the game is closed) it causes some minor micro stuttering. Not much but enough to bug me. I tried fiddling with all the settings but it didn't help.

If I had to guess it's polling something (processes to check if the game is running or checking if there are log files in ED's folder - even if it's empty) in a loop without any tiny delay which causes the stuttering. Moving the window around is also choppy which would also indicate the same thing (doing something in loop without any ms of delay).

I love this tool but this bugs the hell out of me.

**Comment by Marginal** [comment] 2016-09-05 15:48
The app polls the game's current log file every 5 seconds, which should use ~0% CPU (you can check this in Task Manager).

Are you running the app on top of your game window with "Always on top"? If so, this might be possibly be the cause of the stuttering - the graphics drivers have to work a bit harder since they don't have exclusive use of the screen. Does it help if you turn off "Always on top"?

Moving the window around in Dark Theme mode does appear choppy. This is a side-effect of removing the normal window decoration (e.g. titlebar) but is unrelated to your problem since the window isn't redrawn unless you're moving it or there is new information to display.

**Comment by bathrobehero** [comment] 2016-09-05 15:59
The CPU usage is 0%. The always on top option has no effect. GPU usage is 1% with the game not running both with and without EDMC with the dark theme. The light theme does seem to be responsive but the system still have microstuttering.

For now I'm running EDMC from a remote PC scanning the shared log folder to avoid the local stutter and I guess I'd have to settle with that.

**Comment by Marginal** [comment] 2016-09-05 16:58
I would expect EDMC to cause very low CPU and GPU loads. But it is surprising that it's causing you stuttering at these low loads. Do you also see this effect if you run something innocuous like Notepad on the same machine?

Nevertheless I'm glad that you have a solution of sorts.

**Closed** 2016-09-07 22:06 UTC
Labels: working as designed
