### ISSUE TITLE
400 Client Error: Bad Request

### ISSUE THREAD

**Issue by zenque** [Marginal/EDMarketConnector#117] opened 2016-05-31 05:08 UTC
1) Run EDMC
2) click Update
3) Sending data to EDDN
4) 400 Client Error: Bad Request
What happens?  Only I have a problem?

**Comment by IamNovus** [comment] 2016-05-31 05:12
I have the same. bummer

**Comment by AnthorNet** [comment] 2016-05-31 05:35
Please close in favor of #113

**Comment by Marginal** [comment] 2016-05-31 06:20
Duplicate of #113

**Closed by Marginal** 2016-05-31 06:20 UTC
