### ISSUE TITLE
Trying to update prices of station Bhada,Resnick Settlement

### ISSUE THREAD

**Issue by Solstic3** [Marginal/EDMarketConnector#80] opened 2016-01-18 20:52 UTC
It seems that the commidity prices have not been updates for a while so I wanted to try but the tool keeps on giving me an error that it is not able to retrieve any market information.

**Comment by Marginal** [comment] 2016-01-19 00:18
Duplicate of #6

**Closed by Marginal** 2016-01-19 00:18 UTC
Labels: duplicate
