### ISSUE TITLE
Suddenly can't login to inara

### ISSUE THREAD

**Issue by nemesyssoft** [Marginal/EDMarketConnector#269] opened 2017-11-17 05:03 UTC
I checked, double-checked and triple-checked my login on Inara. EDMC keeps reporting:

Inara: Can't login.

I'm using the latest version, 2.4.6.1.

I can't believe I'm the only one with this issue?

**Comment by Jetkar** [comment] 2017-11-17 07:42
I came across this yesterday, What I did was launch the game and then waited till I was passed the main menu in solo / open mode and then launched EDMC it worked for me. I suggest you try that.

**Comment by Marginal** [comment] 2017-11-17 08:01
Duplicate of #262

**Closed by Marginal** 2017-11-17 08:01 UTC

**Comment by nemesyssoft** [comment] 2017-11-17 14:50
Thanks @Jetkar , I will try that.

**Comment by nemesyssoft** [comment] 2017-11-18 05:41
OK, I launched the game, then I waited until I was logged in, then I launched EDMC. No change. It stubbornly reports "Can't login". Btw, I don't know why I would have to wait to be logged in the game for the inara connection to work. The login to inara doesn't have anything to do with the game.

And I don't understand why my issue was closed. There is clearly a bug somewhere. I did logout from inara a couple to times and relogged without any problem. So, the issue is really with EDMC and it's a bit annoying.

**Comment by Jetkar** [comment] 2017-11-18 09:05
Ok it was worth the try as I had a similar problem that has resolved itself. EDMC owner has closed your thread and look at #262 thread for possible solution.

**Comment by nemesyssoft** [comment] 2017-11-18 15:46
I finally checked #262 and removed the inara plugin so, well, it did resolve the issue, as what was causing the issue was removed.

**Comment by Jetkar** [comment] 2017-11-18 15:55
That's great. I have a another problem with EDMC  and looking for a solution.
