### ISSUE TITLE
Engineer data is missing

### ISSUE THREAD

**Issue by bazzawill** [Marginal/EDMarketConnector#247] opened 2017-10-07 20:02 UTC
Hi guys
So now the ED API appears to resolved I had thought module engineering would be available in 2.4, so far I cannot see this

**Comment by sharkismyname** [comment] 2017-10-07 20:18
Looks like we can see it in Shipyard but not Coriolis.

**Comment by bazzawill** [comment] 2017-10-07 20:57
Ah I see, ok can switch to shipyard for the time being

**Comment by Marginal** [comment] 2017-10-08 01:18
Duplicate of #246

**Closed by Marginal** 2017-10-08 01:18 UTC
