### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by bigblock116** [Marginal/EDMarketConnector#48] opened 2015-12-16 05:05 UTC
Receiving an Error:Server is down message when trying to Update for the first time.

**Comment by staticextasy** [comment] 2015-12-16 05:32
+1 for having this issue.

**Comment by Heater338** [comment] 2015-12-16 11:21
Same issue here, But I think it's because of the 2.0 update yesterday, Hope it will be back up soon.

**Comment by Marginal** [comment] 2015-12-16 13:35
Duplicate of #46

**Closed by Marginal** 2015-12-16 13:35 UTC
Labels: duplicate
